### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by fornof** [nmajor25/companies-hiring-remote-devs#3]
ark link directs to ark.io/careers which is a dead link

**Comment by fornof** [comment]
https://jobs.lever.co/airship dead link

**Comment by nmajor25** [comment]
Looks like Ark is no longer hiring. Can't find their career page anymore. So they should be removed.

And it looks like Airship changed the URL of their job listing page. So their link needs to be updated to this: https://www.airship.com/company/careers/#open-positions.

Thanks for pointing these out @fornof 😄
