### ISSUE TITLE
not fully remote algolia

### ISSUE THREAD

**Issue by fornof** [nmajor25/companies-hiring-remote-devs#4]
https://www.algolia.com/careers/ 
from the senior backend engineer post and data pipeline post: 

The majority of employees will be able to choose if, and when, they come into an office on a regular basis. There will be times when our people are asked to come into an office for “moments that matter:” activities like critical planning meetings and team social gatherings.  Beyond those events, 80% of our workforce may choose the location from where they work in the country in which they were hired.

**Comment by nmajor25** [comment]
I would still consider that a remote position. Even though you may need to go meet in person a few times a year.

I left a note in the list for them that signifies they are hybrid remote.
